use application "polytope";

#Each intersection whose volume is computed corresponds to a set of indices I =
#{i_0 i_1 i_2 ... i_{k-1}}.  If the volume of the k polytopes is null already
#then there is no point in looking at supersets of I.  It is possible that this
#simple modification already suffices to compute the total abstract probability.

# volume of a union of polytopes (in the same space); by inclusion-exclusion
sub vol_union(@) {
  my $n = scalar(@_);
  my $total = 0;
  my $sign = 1;
  for (my $k=1; $k<=$n; ++$k) {
    my @idx = @{ all_subsets_of_k(sequence(0,$n), $k) };
    my $v = 0;
    foreach my $subset (@idx) {
      $v += intersection(@_[@$subset])->VOLUME; 
    }
    $total += $sign * $v;
    $sign = -$sign;
  }
  return $total;
}


# union of moduli cones according to Theorem 5.1
# labels: uvwxyz

sub honeycomb_moduli() {
  my $simplex=simplex(6);
  my $non_negative=$simplex->FACETS;

  # automorphisms: Sym(4) of order 24

  # Graph 1 is realizable if and only if max{x, y} ≤ u, max{x, z} ≤ v, and max{y, z} < w, where ...
  my $xy_u=new Matrix( [0, 1,0,0, -1,0,0], [0, 1,0,0, 0,-1,0] );
  my $xz_v=new Matrix( [0, 0,1,0, -1,0,0], [0, 0,1,0, 0,0,-1] );
  my $yz_w=new Matrix( [0, 0,0,1, 0,-1,0], [0, 0,0,1, 0,0,-1] );
  my $Muvw=new Polytope(INEQUALITIES=>$non_negative/$xy_u/$xz_v/$yz_w);
  
  # Graph 1 automorphism taking u->y, v->w, w->z, x->u, y->x, z->v
  my $ux_y=new Matrix( [0,-1,0,0,0,1,0], [0,0,0,0,-1,1,0] );
  my $uv_w=new Matrix( [0,-1,0,1,0,0,0], [0,0,-1,1,0,0,0] );
  my $vx_z=new Matrix( [0,0,0,0,-1,0,1], [0,0,-1,0,0,0,1] );
  my $Mywz=new Polytope(INEQUALITIES=>$non_negative/$ux_y/$uv_w/$vx_z);
  
  # Graph 1 automorphism taking u->x, v->v, w->z, x->u, y->y, z->w
  my $uy_x=new Matrix( [0,-1,0,0,1,0,0], [0,0,0,0,1,-1,0] );
  my $uw_v=new Matrix( [0,-1,1,0,0,0,0], [0,0,1,-1,0,0,0] );
  my $yw_z=new Matrix( [0,0,0,0,0,-1,1], [0,0,0,-1,0,0,1] );
  my $Mxvz=new Polytope(INEQUALITIES=>$non_negative/$uy_x/$uw_v/$yw_z);
  
  # Graph 1 automorphism taking u->u, v->x, w->y, x->v, y->w, z->z
  my $vw_u=new Matrix( [0,1,-1,0,0,0,0], [0,1,0,-1,0,0,0] );
  my $vz_x=new Matrix( [0,0,-1,0,1,0,0], [0,0,0,0,1,0,-1]);
  my $wz_y=new Matrix( [0,0,0,-1,0,1,0],[0,0,0,0,0,1,-1]);
  my $Muxy=new Polytope(INEQUALITIES=>$non_negative/$vw_u/$vz_x/$wz_y);

  return [ $Muvw, $Mywz, $Mxvz, $Muxy ];
}

sub mickey_mouse_moduli() {
  my $simplex=simplex(6);
  my $non_negative=$simplex->FACETS;

  # automorphism group of order 16, one orbit of 8 CLOSED cones

  # Graph 2 is realizable if and only if v ≤ u, y ≤ z, and w + max{v, y} ≤ x, where ...
  my $vu_yz=new Matrix( [0, 1,-1,0, 0,0,0], [0, 0,0,0, 0,-1,1] );
  my $w_vy_x=new Matrix( [0, 0,-1,-1, 1,0,0], [0, 0,0,-1, 1,-1,0] );
  my $M1=new Polytope(INEQUALITIES=>$non_negative/$vu_yz/$w_vy_x);
  # (wx)
  my $x_vy_w=new Matrix( [0, 0,-1,1, -1,0,0], [0, 0,0,1, -1,-1,0] );
  my $M2=new Polytope(INEQUALITIES=>$non_negative/$vu_yz/$x_vy_w);
  
  # Graph 2 automorphism taking u->v, v->u, w->w, x->x, y->y, z->z
  my $uv_yz=new Matrix( [0,-1,1,0,0,0,0], [0,0,0,0,0,-1,1] );
  my $w_uy_x=new Matrix( [0,-1,0,-1,1,0,0], [0,0,0,-1,1,-1,0] );
  my $Muv1=new Polytope(INEQUALITIES=>$non_negative/$uv_yz/$w_uy_x);
  # (wx)
  my $x_uy_w=new Matrix( [0,-1,0,1,-1,0,0], [0,0,0,1,-1,-1,0] );
  my $Muv2=new Polytope(INEQUALITIES=>$non_negative/$uv_yz/$x_uy_w);
  
  # Graph 2 automorphism taking u->u, v->v, w->w, x->x, y->z, z->y
  my $vu_zy=new Matrix( [0,1,-1,0,0,0,0], [0,0,0,0,0,1,-1] );
  my $w_vz_x=new Matrix( [0,0,-1,-1,1,0,0], [0,0,0,-1,1,0,-1] );
  my $Myz1=new Polytope(INEQUALITIES=>$non_negative/$vu_zy/$w_vz_x);
  # (wx)
  my $x_vz_w=new Matrix( [0,0,-1,1,-1,0,0], [0,0,0,1,-1,0,-1] );
  my $Myz2=new Polytope(INEQUALITIES=>$non_negative/$vu_zy/$x_vz_w);
  
  # Graph 2 automorphism taking u->v, v->u, w->w, x->x, y->z, z->y
  my $uv_zy=new Matrix( [0,-1,1,0,0,0,0], [0,0,0,0,0,1,-1] );
  my $w_uz_x=new Matrix( [0,-1,0,-1,1,0,0], [0,0,0,-1,1,0,-1] );
  my $Muvyz1=new Polytope(INEQUALITIES=>$non_negative/$uv_zy/$w_uz_x);
  # (wx)
  my $x_uz_w=new Matrix( [0,-1,0,1,-1,0,0], [0,0,0,1,-1,0,-1] );
  my $Muvyz2=new Polytope(INEQUALITIES=>$non_negative/$uv_zy/$x_uz_w);

  return [ $M1, $M2, $Muv1, $Muv2, $Myz1, $Myz2, $Muvyz1, $Muvyz2 ];
}

sub one_bridge_moduli() {
  my $simplex=simplex(6);
  my $non_negative=$simplex->FACETS;

  # automorphism group generated by (uv) and (wx), order 4

  # Graph 3 is realizable if and only if w < x and one of the following conditions holds:
  #   v + w = x and v < u, or                                                      EQUALITY IGNORED
  #   v + w < x ≤ v + 3w and v ≤ u, or
  #   v + 3w < x ≤ v + 4w and v ≤ u ≤ 3v/2, or (Ralph's correction from July 16th)
  #   v + 4w < x ≤ v + 5w and v=u. (Ralph's correction from July 16th)             EQUALITY IGNORED
  #   w+v<x≤4w+v and u=2v EQUALITY ADDED 12 Sept. 2014
  my $wx   =new Matrix( [[0, 0,0,-1, 1,0,0]] );
  my $wv_x =new Matrix( [0, 0,-1,-1, 1,0,0], [0, 0,1,3, -1,0,0], [0, 1,-1,0, 0,0,0] );
  my $v3w_x=new Matrix( [0,0,-1,-3,1,0,0], [0,0,1,4,-1,0,0], [0,1,-1,0,0,0,0], [0,-1,3/2,0,0,0,0] );
  my $wv_x_4wv=new Matrix( [0,0,-1,-1,1,0,0],[0,0,1,4,-1,0,0],[0,1,-2,0,0,0,0],[0,-1,2,0,0,0,0] );
  my $M1=new Polytope(INEQUALITIES=>$non_negative/$wx/$wv_x);
  my $M2=new Polytope(INEQUALITIES=>$non_negative/$wx/$v3w_x);
  my $M3=new Polytope(INEQUALITIES=>$non_negative/$wx/$wv_x_4wv);
  # (wx)
  my $xw   =new Matrix( [[0, 0,0,1, -1,0,0]] );
  my $xv_w =new Matrix( [0, 0,-1,1, -1,0,0], [0, 0,1,-1, 3,0,0], [0, 1,-1,0, 0,0,0] );
  my $v3x_w=new Matrix( [0,0,-1,1,-3,0,0], [0,0,1,-1,4,0,0], [0,1,-1,0,0,0,0], [0,-1,3/2,0,0,0,0] );
  my $xv_w_4xv=new Matrix( [0,0,-1,1,-1,0,0],[0,0,1,-1,4,0,0],[0,1,-2,0,0,0,0],[0,-1,2,0,0,0,0] );
  my $M4=new Polytope(INEQUALITIES=>$non_negative/$xw/$xv_w);
  my $M5=new Polytope(INEQUALITIES=>$non_negative/$xw/$v3x_w);
  my $M6=new Polytope(INEQUALITIES=>$non_negative/$xw/$xv_w_4xv);
  
  # Graph 3 automorphism taking u->v, v->u, w->w, x->x, y->y, z->z
  my $wx   =new Matrix( [[0, 0,0,-1, 1,0,0]] );
  my $wu_x =new Matrix( [0, -1,0,-1, 1,0,0], [0, 1,0,3, -1,0,0], [0, -1,1,0, 0,0,0] );
  my $u3w_x=new Matrix( [0,-1,0,-3,1,0,0], [0,1,0,4,-1,0,0], [0,-1,1,0,0,0,0], [0,3/2,-1,0,0,0,0] );
  my $wu_x_4wu=new Matrix( [0,-1,0,-1,1,0,0],[0,1,0,4,-1,0,0],[0,-2,1,0,0,0,0],[0,2,-1,0,0,0,0] );
  my $Muv1=new Polytope(INEQUALITIES=>$non_negative/$wx/$wu_x);
  my $Muv2=new Polytope(INEQUALITIES=>$non_negative/$wx/$u3w_x);
  my $Muv3=new Polytope(INEQUALITIES=>$non_negative/$wx/$wu_x_4wu);
  # (wx)
  my $xw   =new Matrix( [[0, 0,0,1, -1,0,0]] );
  my $xu_w =new Matrix( [0, -1,0,1, -1,0,0], [0, 1,0,-1, 3,0,0], [0, -1,1,0, 0,0,0] );
  my $u3x_w=new Matrix( [0,-1,0,1,-3,0,0], [0,1,0,-1,4,0,0], [0,-1,1,0,0,0,0], [0,3/2,-1,0,0,0,0] );
  my $xu_w_4xu=new Matrix( [0,-1,0,1,-1,0,0],[0,1,0,-1,4,0,0],[0,-2,1,0,0,0,0],[0,2,-1,0,0,0,0] );
  my $Muv4=new Polytope(INEQUALITIES=>$non_negative/$xw/$xu_w);
  my $Muv5=new Polytope(INEQUALITIES=>$non_negative/$xw/$u3x_w);
  my $Muv6=new Polytope(INEQUALITIES=>$non_negative/$xu_w_4xu);
  
  return [ $M1, $M2, $M3, $M4, $M5, $M6, $Muv1, $Muv2, $Muv3, $Muv4, $Muv5, $Muv6 ];
}

sub two_bridge_moduli() {
  my $simplex=simplex(6);
  my $non_negative=$simplex->FACETS;

  # Graph 4 is realizable if and only if w < x ≤ 2w.
  my $wx=new Matrix( [0, 0,0,-1, 1,0,0], [0, 0,0,2, -1,0,0] );
  my $Mwx=new Polytope(INEQUALITIES=>$non_negative/$wx);
  # (xw)
  my $xw=new Matrix( [0, 0,0,1, -1,0,0], [0, 0,0,-1, 2,0,0] );
  my $Mxw=new Polytope(INEQUALITIES=>$non_negative/$xw);
  
  # All other automorphisms of Graph 4 are accounted for, as the inequality w < x ≤ 2w only involves x and w.

  return [ $Mwx, $Mxw ];
}

sub probability($) {
  my ($poly_list)=@_;
  my $simplex=simplex(6);
  return vol_union(@$poly_list) / $simplex->VOLUME;
}

sub print_probability_table() {
  my  $M7=honeycomb_moduli();    my  $p7=probability($M7);
  my  $M3=mickey_mouse_moduli(); my  $p3=probability($M3);
  my  $M0=one_bridge_moduli();   my  $p0=probability($M0);
  my $M31=two_bridge_moduli();   my $p31=probability($M31);
  print "honeycomb: ", $p7, "=", (convert_to<Float>($p7)), "\n";
  print "mickey_mouse: ", $p3, "=", (convert_to<Float>($p3)), "\n";
  print "one_bridge: ", $p0, "=", (convert_to<Float>($p0)), "\n";
  print "two_bridge: ", $p31, "=", (convert_to<Float>($p31)), "\n";
  my $t=($p7+$p3+$p0+$p31)/5; # take the non-realizable graph (303) into account
  print "TOTAL: ", $t, "=", (convert_to<Float>($t)), "\n";
}

# Local Variables:
# mode: cperl
# c-basic-offset:2
# End:
